export const STATUSES = Object.freeze({
  PENDING: "PENDING",
  IN_REVIEW: "IN_REVIEW",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
});

export const DEALER_APPLICATION_STATUS = Object.freeze({
  PENDING: "PENDING",
  IN_REVIEW: "IN_REVIEW",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
});

export const DEALER_STATUS = Object.freeze({
  VERIFIED: "VERIFIED",
  SUSPENDED: "SUSPENDED",
});

export const ORDER_STATUS = Object.freeze({
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  SENT_TO_DISPATCHER: "SENT_TO_DISPATCHER",
  DISPATCHED: "DISPATCHED",
  DELIVERED: "DELIVERED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
});

export const PAYMENT_METHOD = Object.freeze({
  CASH: "CASH",
  ONLINE: "ONLINE",
  CHEQUE: "CHEQUE",
  BANK_GUARANTEE: "BANK_GUARANTEE",
  CREDIT: "CREDIT",
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING_DECLARATION: "PENDING_DECLARATION", // method selected but no proof / no check
  PENDING_VERIFICATION: "PENDING_VERIFICATION", // proof uploaded/declared
  VERIFIED: "VERIFIED", // money confirmed
  REJECTED: "REJECTED",
  PARTIAL: "PARTIAL",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
});

export const SHIPMENT_STATUS = Object.freeze({
  QUEUED: "QUEUED",
  PICKING: "PICKING",
  DISPATCHED: "DISPATCHED",
  DELIVERED: "DELIVERED",
});
